// Generated by `blocks init <name> --mode webapp`. The auth + paid-agent + sign-out
// plumbing below is the part of the scaffold the persona could not
// reproduce on their own — keep it as-is unless you know what you're doing.
//
// Per-agent I/O wiring is generated from each agent's card snapshot at
// init time. Re-run `blocks init` in a fresh directory to refresh against
// the latest card.
// Agent: unknown_input — card snapshot taken 2026-05-09. Re-run `blocks init` to refresh.
// Inputs:  weird (application/x-acme-blob)
// Outputs: result (application/x-acme-out)

(function () {
  const signInBtn = document.getElementById('sign-in-btn');
  const signOutBtn = document.getElementById('sign-out-btn');
  const authError = document.getElementById('auth-error');

  // Map an error to a user-visible message. Used by both the sign-in
  // catch (where errors are typically BlocksAuthError from the popup
  // flow) and per-send catches (where InsufficientBalance comes from
  // the backend RPC for paid agents the caller can't afford). One source
  // of truth so the two catches stay in sync.
  function blocksErrorMessage(err) {
    if (err instanceof BlocksAuth.BlocksAuthError) {
      return 'Sign-in error: ' + err.message;
    }
    if (err && err.data && err.data.code === 'InsufficientBalance') {
      return 'This agent requires funds to use. Add a balance in your Blocks dashboard.';
    }
    return 'Unexpected error: ' + (err && err.message ? err.message : String(err));
  }

  // Render an artifact's bytes into outputEl based on its own mimeType.
  // Used for: (a) untagged artifacts (event.outputId may be undefined per
  // SDK_CONTRACT §9.1), (b) outputId values that don't match any declared
  // output, (c) the post-terminal listArtifacts() defensive fallback.
  function renderArtifactByMime(bytes, mimeType, outputEl) {
    const mt = mimeType || '';
    if (mt === 'application/json') {
      try {
        const parsed = JSON.parse(new TextDecoder().decode(bytes));
        outputEl.textContent += JSON.stringify(parsed, null, 2);
        return;
      } catch (_) {
        outputEl.textContent += new TextDecoder().decode(bytes);
        return;
      }
    }
    if (mt.indexOf('text/') === 0) {
      outputEl.textContent += new TextDecoder().decode(bytes);
      return;
    }
    if (mt.indexOf('image/') === 0) {
      const blob = new Blob([bytes], { type: mt });
      const img = document.createElement('img');
      img.className = 'output';
      img.src = URL.createObjectURL(blob);
      outputEl.appendChild(img);
      return;
    }
    const blob = new Blob([bytes], mt ? { type: mt } : undefined);
    const link = document.createElement('a');
    link.href = URL.createObjectURL(blob);
    link.download = 'artifact';
    link.textContent = 'Download artifact' + (mt ? ' (' + mt + ')' : '');
    outputEl.appendChild(link);
  }

  // Read and validate a pipe-task duration from a number input. Pipe tasks
  // require an integer number of MINUTES in [1, 43200] (1 minute … 30 days).
  // The SDK also validates before the request leaves the browser; this surfaces
  // a friendly error first and keeps the bad value from being sent.
  function readPipeDuration(el) {
    const v = parseInt(el && el.value, 10);
    if (!Number.isInteger(v) || v < 1 || v > 43200) {
      throw new Error('Duration must be a whole number of minutes between 1 and 43200.');
    }
    return v;
  }

  // Single-agent scaffold: signInAndGetClient returns one TaskClient.
  let clients = null;

  async function attemptSignIn() {
    authError.textContent = '';
    try {
      const client = await BlocksAuth.signInAndGetClient({ agent: "unknown_input" });
      clients = { ["unknown_input"]: client };
      signInBtn.hidden = true;
      signOutBtn.hidden = false;
      if (clients["unknown_input"]) document.getElementById('section-unknown_input').hidden = false;
      return true;
    } catch (err) {
      authError.textContent = blocksErrorMessage(err);
      return false;
    }
  }

  signInBtn.addEventListener('click', attemptSignIn);

  // Auto-resume on page load: silent refresh ONLY when the stored partition exactly matches this page's (backend, origin, agents); otherwise wait for click.
  async function hasExactStoredEmbedSession() {
    try {
      if (typeof BlocksAuth === 'undefined' || typeof BlocksAuth.computePartitionKey !== 'function') return false;
      const raw = localStorage.getItem('blocks-auth-active-sessions-v1');
      if (!raw) return false;
      const arr = JSON.parse(raw);
      if (!Array.isArray(arr) || arr.length === 0) return false;
      const dev = (typeof window !== 'undefined' && window.__BLOCKS_EMBED_DEV__) || null;
      const backendBaseUrl = (dev && dev.backendBaseUrl) ? dev.backendBaseUrl : "https://blocks.ai";
      const pageOrigin = window.location.origin;
      const agentNames = ["unknown_input"];
      const expected = await BlocksAuth.computePartitionKey({ backendBaseUrl, pageOrigin, agentNames });
      return arr.some(function (entry) { return entry && entry.partitionKey === expected; });
    } catch (_) {
      return false;
    }
  }
  hasExactStoredEmbedSession().then(function (yes) {
    if (yes) attemptSignIn();
  });

  signOutBtn.addEventListener('click', async () => {
    // signOut clears the partitioned localStorage entry for this origin;
    // reload to reset the in-page state.
    await BlocksAuth.signOut();
    window.location.reload();
  });

  // === Agent: unknown_input ===
  document.getElementById('send-unknown_input').addEventListener('click', async () => {
    const sendBtn = document.getElementById('send-unknown_input');
    const outputEl = document.getElementById('output-unknown_input');
    outputEl.textContent = '';
    sendBtn.disabled = true;
    const renderedRefs = new Set();
    try {
      const client = clients["unknown_input"];
      const requestParts = [];
      // TODO: input "weird" has unrecognized contentType "application/x-acme-blob".
      // Sending JSON-encoded text as a defensive default. Confirm with
      // the agent's owner what the handler reads.
      const ta_0 = document.getElementById("input-unknown_input-weird");
      try { JSON.parse(ta_0.value); } catch (e) { throw new Error('input ' + "weird" + ': invalid JSON: ' + e.message); }
      requestParts.push({ partId: "weird", text: ta_0.value });
      // TODO: agent did not declare a schema for input "weird". Replace the
      //       textarea default with whatever your handler accepts.
      const session = await client.sendMessage({
        agentName: "unknown_input",
        taskKind: "request",
        requestParts,
      });
      // Card declares exactly 1 output — route every artifact here
      // regardless of event.outputId. outputId is OPTIONAL per
      // SDK_CONTRACT §9.1; we don't gate on its presence.
      session.onArtifact(async (event) => {
        if (renderedRefs.has(event.artifactRef)) return;
        renderedRefs.add(event.artifactRef);
        let bytes;
        try {
          const downloaded = await session.downloadArtifact(event.artifactRef);
          bytes = downloaded.data;
        } catch (err) {
          outputEl.textContent += '\n[download failed: ' + err.message + ']';
          return;
        }
        // === Output: "result" (application/x-acme-out, guaranteed=false) ===
        // TODO: output "result" has unrecognized contentType "application/x-acme-out". Rendered as download.
        const blob = new Blob([bytes]);
        const link = document.createElement('a');
        link.href = URL.createObjectURL(blob);
        link.download = "result";
        link.textContent = 'Download ' + "result";
        outputEl.appendChild(link);
      });
      const terminal = await session.waitForTerminal();
      if (terminal.state !== 'completed') {
        outputEl.textContent += '\n[' + (terminal.error || terminal.reason || 'task ' + terminal.state) + ']';
      }
      for (const ref of session.listArtifacts()) {
        if (renderedRefs.has(ref)) continue;
        renderedRefs.add(ref);
        try {
          const downloaded = await session.downloadArtifact(ref);
          renderArtifactByMime(downloaded.data, ref.mimeType, outputEl);
        } catch (err) {
          outputEl.textContent += '\n[download failed: ' + err.message + ']';
        }
      }
    } catch (err) {
      outputEl.textContent += '\n[' + blocksErrorMessage(err) + ']';
    } finally {
      sendBtn.disabled = false;
    }
  });

})();
