package scaffold

import (
	"context"
	"net/http"
	"net/http/httptest"
	"os"
	"os/exec"
	"path/filepath"
	"testing"

	esbuild "github.com/evanw/esbuild/pkg/api"
	"github.com/pubnub/blocks-sdk/cli/internal/blocksapi"
	"github.com/pubnub/blocks-sdk/cli/internal/cardfetch"
	"github.com/pubnub/blocks-sdk/cli/internal/wizard"
)

// pyCompile runs `python3 -m py_compile <file>`. Returns nil on success,
// error with stderr on syntax failure. Skips the caller test if python3
// is not on PATH. This catches syntactic regressions in template expansion;
// it does NOT catch runtime issues such as NameError or missing imports.
func pyCompile(t *testing.T, path string) {
	t.Helper()
	py, err := exec.LookPath("python3")
	if err != nil {
		t.Skipf("python3 not on PATH; skipping Python parse smoke test: %v", err)
	}
	cmd := exec.Command(py, "-m", "py_compile", path)
	if out, err := cmd.CombinedOutput(); err != nil {
		t.Fatalf("python3 -m py_compile %s failed: %v\n%s", path, err, out)
	}
}

func TestScaffoldedProviderPythonParses(t *testing.T) {
	dir := filepath.Join(t.TempDir(), "smoke_agent")
	cfg := wizard.Config{
		Name:              "smoke_agent",
		Description:       "smoke",
		Language:          "python",
		Mode:              "provider",
		Concurrency:       1,
		ExpectedInstances: 1,
		TaskKinds:         []string{"request"},
	}
	if err := Project(dir, cfg, nil); err != nil {
		t.Fatal(err)
	}
	pyCompile(t, filepath.Join(dir, "handler.py"))
	pyCompile(t, filepath.Join(dir, "trigger.py"))
}

// tsParse calls esbuild.Transform with the TypeScript loader. It only
// checks syntactic validity (not types) — sufficient to catch template
// regressions. Reads the file from disk for accurate diagnostics.
func tsParse(t *testing.T, path string) {
	t.Helper()
	src, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read %s: %v", path, err)
	}
	result := esbuild.Transform(string(src), esbuild.TransformOptions{
		Loader:     esbuild.LoaderTS,
		LogLevel:   esbuild.LogLevelSilent,
		Sourcefile: path,
	})
	if len(result.Errors) > 0 {
		t.Fatalf("esbuild parse errors in %s:\n%+v", path, result.Errors)
	}
}

func TestScaffoldedProviderNodeParses(t *testing.T) {
	dir := filepath.Join(t.TempDir(), "smoke_agent")
	cfg := wizard.Config{
		Name:              "smoke_agent",
		Description:       "smoke",
		Language:          "node",
		Mode:              "provider",
		Concurrency:       1,
		ExpectedInstances: 1,
		TaskKinds:         []string{"request"},
	}
	if err := Project(dir, cfg, nil); err != nil {
		t.Fatal(err)
	}
	tsParse(t, filepath.Join(dir, "handler.ts"))
	tsParse(t, filepath.Join(dir, "trigger.ts"))
}

func TestScaffoldedConsumerNodeParses(t *testing.T) {
	dir := filepath.Join(t.TempDir(), "my_consumer")
	cfg := wizard.Config{
		Name:        "my_consumer",
		Description: "my_consumer consumer",
		Language:    "node",
		Mode:        "consumer",
	}
	if err := Project(dir, cfg, nil); err != nil {
		t.Fatal(err)
	}
	tsParse(t, filepath.Join(dir, "index.ts"))
}

func TestScaffoldedConsumerPythonParses(t *testing.T) {
	dir := filepath.Join(t.TempDir(), "my_consumer")
	cfg := wizard.Config{
		Name:        "my_consumer",
		Description: "my_consumer consumer",
		Language:    "python",
		Mode:        "consumer",
	}
	if err := Project(dir, cfg, nil); err != nil {
		t.Fatal(err)
	}
	pyCompile(t, filepath.Join(dir, "main.py"))
}

// TestScaffoldedWebappAppJSParses verifies the webapp scaffold generated by
// Project (driven via the same cardfetch path that cmd/init uses) emits a
// syntactically valid app.js. Uses `node --check` when available; falls
// back to esbuild's JS loader otherwise.
func TestScaffoldedWebappAppJSParses(t *testing.T) {
	body, err := os.ReadFile(filepath.Join("..", "cardfetch", "testdata", "echo2.json"))
	if err != nil {
		t.Fatalf("read echo2 fixture: %v", err)
	}
	srv := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Content-Type", "application/json")
		w.WriteHeader(http.StatusOK)
		_, _ = w.Write(body)
	}))
	defer srv.Close()

	client := blocksapi.NewClient(srv.URL, "smoke-key")
	card, err := cardfetch.Fetch(context.Background(), client, "echo2")
	if err != nil {
		t.Fatalf("Fetch: %v", err)
	}

	dir := filepath.Join(t.TempDir(), "smoke_webapp")
	cfg := wizard.Config{
		Name:   "smoke_webapp",
		Mode:   "webapp",
		Agents: []string{"echo2"},
	}
	if err := Project(dir, cfg, []*cardfetch.AgentCard{card}); err != nil {
		t.Fatalf("Project: %v", err)
	}

	appJSPath := filepath.Join(dir, "web", "app.js")
	if _, err := os.Stat(appJSPath); err != nil {
		t.Fatalf("expected web/app.js to exist: %v", err)
	}

	if node, err := exec.LookPath("node"); err == nil {
		cmd := exec.Command(node, "--check", appJSPath)
		if out, err := cmd.CombinedOutput(); err != nil {
			t.Fatalf("node --check %s failed: %v\n%s", appJSPath, err, out)
		}
	} else {
		// Fall back to esbuild's JS parser if node isn't available.
		src, err := os.ReadFile(appJSPath)
		if err != nil {
			t.Fatalf("read app.js: %v", err)
		}
		result := esbuild.Transform(string(src), esbuild.TransformOptions{
			Loader:     esbuild.LoaderJS,
			LogLevel:   esbuild.LogLevelSilent,
			Sourcefile: appJSPath,
		})
		if len(result.Errors) > 0 {
			t.Fatalf("esbuild parse errors in %s:\n%+v", appJSPath, result.Errors)
		}
	}
}
