"""Report template and file output utilities."""

import os
from datetime import datetime

REPORT_TEMPLATE = """# Competitive Analysis: Real-Time Communication Platforms
**Generated: {date}**

---

## Executive Summary

{executive_summary}

---

## Market Overview

{market_overview}

---

## Company Profiles

### PubNub

{pubnub_profile}

### Ably

{ably_profile}

### Pusher

{pusher_profile}

### Firebase (Google)

{firebase_profile}

---

## Feature Comparison

{feature_comparison}

---

## Pricing Comparison

{pricing_comparison}

---

## Strategic Recommendations

{strategic_recommendations}

---

## Sources

{sources}

---

*Report generated by LangChain Business Strategy Agent*
"""


def save_report(content, filename=None):
    """Save the report content to the output directory.

    Args:
        content: Markdown report content.
        filename: Optional filename. Defaults to timestamped name.

    Returns:
        The path to the saved report file.
    """
    output_dir = os.path.join(os.path.dirname(os.path.abspath(__file__)), "output")
    os.makedirs(output_dir, exist_ok=True)

    if filename is None:
        timestamp = datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
        filename = f"competitive_analysis_{timestamp}.md"

    filepath = os.path.join(output_dir, filename)
    with open(filepath, "w", encoding="utf-8") as f:
        f.write(content)

    return filepath
