// Generated by `blocks init <name> --mode webapp`. The auth + paid-agent + sign-out
// plumbing below is the part of the scaffold the persona could not
// reproduce on their own — keep it as-is unless you know what you're doing.
//
// Per-agent I/O wiring is generated from each agent's card snapshot at
// init time. Re-run `blocks init` in a fresh directory to refresh against
// the latest card.
// Agent: binary_input — card snapshot taken 2026-05-09. Re-run `blocks init` to refresh.
// Inputs:  blob (application/octet-stream)
// Outputs: thumbnail (image/png) report (application/pdf)

(function () {
  const signInBtn = document.getElementById('sign-in-btn');
  const signOutBtn = document.getElementById('sign-out-btn');
  const authError = document.getElementById('auth-error');

  // Map an error to a user-visible message. Used by both the sign-in
  // catch (where errors are typically BlocksAuthError from the popup
  // flow) and per-send catches (where InsufficientBalance comes from
  // the backend RPC for paid agents the caller can't afford). One source
  // of truth so the two catches stay in sync.
  function blocksErrorMessage(err) {
    if (typeof BlocksAuth === 'undefined') {
      return 'The Blocks auth widget failed to load. Check your network connection and reload.';
    }
    if (err instanceof BlocksAuth.BlocksAuthError) {
      return 'Sign-in error: ' + err.message;
    }
    if (err && err.data && err.data.code === 'InsufficientBalance') {
      return 'This agent requires funds to use. Add a balance in your Blocks dashboard.';
    }
    return 'Unexpected error: ' + (err && err.message ? err.message : String(err));
  }

  // Render an artifact's bytes into outputEl based on its own mimeType.
  // Used for: (a) untagged artifacts (event.outputId may be undefined per
  // SDK_CONTRACT §9.1), (b) outputId values that don't match any declared
  // output, (c) the post-terminal listArtifacts() defensive fallback.
  function renderArtifactByMime(bytes, mimeType, outputEl) {
    const mt = mimeType || '';
    if (mt === 'application/json') {
      try {
        const parsed = JSON.parse(new TextDecoder().decode(bytes));
        outputEl.textContent += JSON.stringify(parsed, null, 2);
        return;
      } catch (_) {
        outputEl.textContent += new TextDecoder().decode(bytes);
        return;
      }
    }
    if (mt.indexOf('text/') === 0) {
      outputEl.textContent += new TextDecoder().decode(bytes);
      return;
    }
    if (mt.indexOf('image/') === 0) {
      const blob = new Blob([bytes], { type: mt });
      const img = document.createElement('img');
      img.className = 'output';
      img.src = URL.createObjectURL(blob);
      outputEl.appendChild(img);
      return;
    }
    const blob = new Blob([bytes], mt ? { type: mt } : undefined);
    const link = document.createElement('a');
    link.href = URL.createObjectURL(blob);
    link.download = 'artifact';
    link.textContent = 'Download artifact' + (mt ? ' (' + mt + ')' : '');
    outputEl.appendChild(link);
  }

  // Read and validate a pipe-task duration from a number input. Pipe tasks
  // require an integer number of MINUTES in [1, 43200] (1 minute … 30 days).
  // The SDK also validates before the request leaves the browser; this surfaces
  // a friendly error first and keeps the bad value from being sent.
  function readPipeDuration(el) {
    const v = parseInt(el && el.value, 10);
    if (!Number.isInteger(v) || v < 1 || v > 43200) {
      throw new Error('Duration must be a whole number of minutes between 1 and 43200.');
    }
    return v;
  }

  // Maximum time to wait for the embed-auth widget script (injected in
  // index.html) to define window.BlocksAuth.
  const WIDGET_READY_TIMEOUT_MS = 10000;

  // Resolve once the widget has defined window.BlocksAuth, or to false after
  // WIDGET_READY_TIMEOUT_MS if it never loads. The widget is a large
  // cross-origin bundle injected via a dynamically-created <script>; a
  // dynamically-inserted async=false script is NOT ordered against this
  // deferred app.js, so app.js can run first. Reading window.BlocksAuth
  // synchronously would then see it undefined. Wait instead of assuming.
  function whenBlocksAuthReady(timeoutMs) {
    return new Promise(function (resolve) {
      if (typeof BlocksAuth !== 'undefined') { resolve(true); return; }
      let waited = 0;
      const step = 50;
      const timer = setInterval(function () {
        if (typeof BlocksAuth !== 'undefined') {
          clearInterval(timer);
          resolve(true);
        } else if ((waited += step) >= timeoutMs) {
          clearInterval(timer);
          resolve(false);
        }
      }, step);
    });
  }

  // Single-agent scaffold: signInAndGetClient returns one TaskClient.
  let clients = null;

  function embedBackendBaseUrl() {
    const dev = (typeof window !== 'undefined' && window.__BLOCKS_EMBED_DEV__) || null;
    return (dev && dev.backendBaseUrl) ? dev.backendBaseUrl : "https://app.blocks.ai";
  }

  async function attemptSignIn() {
    authError.textContent = '';
    if (!(await whenBlocksAuthReady(WIDGET_READY_TIMEOUT_MS))) {
      authError.textContent = 'The Blocks auth widget failed to load. Check your network connection and reload.';
      return false;
    }
    try {
      const client = await BlocksAuth.signInAndGetClient({ agent: "binary_input", backendBaseUrl: embedBackendBaseUrl() });
      clients = { ["binary_input"]: client };
      signInBtn.hidden = true;
      signOutBtn.hidden = false;
      if (clients["binary_input"]) document.getElementById('section-binary_input').hidden = false;
      return true;
    } catch (err) {
      authError.textContent = blocksErrorMessage(err);
      return false;
    }
  }

  signInBtn.addEventListener('click', attemptSignIn);

  // Auto-resume on page load: silent refresh ONLY when the stored partition exactly matches this page's (backend, origin, agents); otherwise wait for click.
  async function hasExactStoredEmbedSession() {
    try {
      if (typeof BlocksAuth === 'undefined' || typeof BlocksAuth.computePartitionKey !== 'function') return false;
      const raw = localStorage.getItem('blocks-auth-active-sessions-v1');
      if (!raw) return false;
      const arr = JSON.parse(raw);
      if (!Array.isArray(arr) || arr.length === 0) return false;
      const backendBaseUrl = embedBackendBaseUrl();
      const pageOrigin = window.location.origin;
      const agentNames = ["binary_input"];
      const expected = await BlocksAuth.computePartitionKey({ backendBaseUrl, pageOrigin, agentNames });
      return arr.some(function (entry) { return entry && entry.partitionKey === expected; });
    } catch (_) {
      return false;
    }
  }
  whenBlocksAuthReady(WIDGET_READY_TIMEOUT_MS).then(function () {
    hasExactStoredEmbedSession().then(function (yes) {
      if (yes) attemptSignIn();
    });
  });

  signOutBtn.addEventListener('click', async () => {
    // signOut clears the partitioned localStorage entry for this origin;
    // reload to reset the in-page state.
    await BlocksAuth.signOut();
    window.location.reload();
  });

  // === Agent: binary_input ===
  document.getElementById('send-binary_input').addEventListener('click', async () => {
    const sendBtn = document.getElementById('send-binary_input');
    const outputEl = document.getElementById('output-binary_input');
    outputEl.textContent = '';
    sendBtn.disabled = true;
    const renderedRefs = new Set();
    try {
      const client = clients["binary_input"];
      const requestParts = [];
      // input "blob" is file-class (application/octet-stream) — use filePart() so files <= 16 KB
      // inline and larger files use the pre-signed URL upload flow automatically.
      const fileEl_0 = document.getElementById("input-binary_input-blob");
      const file_0 = fileEl_0.files[0];
      if (!file_0) throw new Error('input ' + "blob" + ': no file selected');
      if (file_0) {
        // SDK filePart() helper picks inline vs upload-URL automatically.
        requestParts.push({
          partId: "blob",
          file: file_0,
          fileName: file_0.name,
          contentType: file_0.type || "application/octet-stream",
        });
      }
      const session = await client.sendMessage({
        agentName: "binary_input",
        taskKind: "request",
        requestParts,
      });
      // Output rendering is dispatched via onArtifact, switching on
      // event.outputId. outputId is OPTIONAL per SDK_CONTRACT §9.1, so
      // untagged or unknown artifacts fall to a mimeType-based renderer.
      session.onArtifact(async (event) => {
        if (renderedRefs.has(event.artifactRef)) return;
        renderedRefs.add(event.artifactRef);
        let bytes;
        try {
          const downloaded = await session.downloadArtifact(event.artifactRef);
          bytes = downloaded.data;
        } catch (err) {
          outputEl.textContent += '\n[download failed: ' + err.message + ']';
          return;
        }
        switch (event.outputId) {
          // === Output: "thumbnail" (image/png, guaranteed=true) ===
          case "thumbnail": {
            const blob = new Blob([bytes], { type: "image/png" });
            const img = document.createElement('img');
            img.className = 'output';
            img.src = URL.createObjectURL(blob);
            outputEl.appendChild(img);
            break;
          }
          // === Output: "report" (application/pdf, guaranteed=false) ===
          case "report": {
            // TODO: output "report" is application/pdf. Rendered as a download link;
            //       replace with whatever your UI needs.
            const blob = new Blob([bytes], { type: "application/pdf" });
            const link = document.createElement('a');
            link.href = URL.createObjectURL(blob);
            link.download = "report";
            link.textContent = 'Download ' + "report";
            outputEl.appendChild(link);
            break;
          }
          default: {
            // Untagged or unknown outputId. Render based on the artifact's
            // own mimeType rather than guessing which declared output it
            // was meant for.
            renderArtifactByMime(bytes, event.artifactRef.mimeType, outputEl);
          }
        }
      });
      const terminal = await session.waitForTerminal();
      if (terminal.state !== 'completed') {
        outputEl.textContent += '\n[' + (terminal.error || terminal.reason || 'task ' + terminal.state) + ']';
      }
      for (const ref of session.listArtifacts()) {
        if (renderedRefs.has(ref)) continue;
        renderedRefs.add(ref);
        try {
          const downloaded = await session.downloadArtifact(ref);
          renderArtifactByMime(downloaded.data, ref.mimeType, outputEl);
        } catch (err) {
          outputEl.textContent += '\n[download failed: ' + err.message + ']';
        }
      }
    } catch (err) {
      outputEl.textContent += '\n[' + blocksErrorMessage(err) + ']';
    } finally {
      sendBtn.disabled = false;
    }
  });

})();
