// Generated by `blocks init <name> --mode webapp`. The auth + paid-agent + sign-out
// plumbing below is the part of the scaffold the persona could not
// reproduce on their own — keep it as-is unless you know what you're doing.
//
// Per-agent I/O wiring is generated from each agent's card snapshot at
// init time. Re-run `blocks init` in a fresh directory to refresh against
// the latest card.
// Agent: complex_multi_input — card snapshot taken 2026-05-09. Re-run `blocks init` to refresh.
// Inputs:  in1 (application/json)  in2 (text/plain)  in3 (application/json)  in4 (application/json)  in5 (application/json)  in6 (application/json)
// Outputs: out1 (text/plain) out2 (application/json) out3 (application/pdf) out4 (image/png)
// Streams: events_a (events, outbound) events_b (bytes, outbound) events_c (events, outbound)

(function () {
  const signInBtn = document.getElementById('sign-in-btn');
  const signOutBtn = document.getElementById('sign-out-btn');
  const authError = document.getElementById('auth-error');

  // Map an error to a user-visible message. Used by both the sign-in
  // catch (where errors are typically BlocksAuthError from the popup
  // flow) and per-send catches (where InsufficientBalance comes from
  // the backend RPC for paid agents the caller can't afford). One source
  // of truth so the two catches stay in sync.
  function blocksErrorMessage(err) {
    if (typeof BlocksAuth === 'undefined') {
      return 'The Blocks auth widget failed to load. Check your network connection and reload.';
    }
    if (err instanceof BlocksAuth.BlocksAuthError) {
      return 'Sign-in error: ' + err.message;
    }
    if (err && err.data && err.data.code === 'InsufficientBalance') {
      return 'This agent requires funds to use. Add a balance in your Blocks dashboard.';
    }
    return 'Unexpected error: ' + (err && err.message ? err.message : String(err));
  }

  // Render an artifact's bytes into outputEl based on its own mimeType.
  // Used for: (a) untagged artifacts (event.outputId may be undefined per
  // SDK_CONTRACT §9.1), (b) outputId values that don't match any declared
  // output, (c) the post-terminal listArtifacts() defensive fallback.
  function renderArtifactByMime(bytes, mimeType, outputEl) {
    const mt = mimeType || '';
    if (mt === 'application/json') {
      try {
        const parsed = JSON.parse(new TextDecoder().decode(bytes));
        outputEl.textContent += JSON.stringify(parsed, null, 2);
        return;
      } catch (_) {
        outputEl.textContent += new TextDecoder().decode(bytes);
        return;
      }
    }
    if (mt.indexOf('text/') === 0) {
      outputEl.textContent += new TextDecoder().decode(bytes);
      return;
    }
    if (mt.indexOf('image/') === 0) {
      const blob = new Blob([bytes], { type: mt });
      const img = document.createElement('img');
      img.className = 'output';
      img.src = URL.createObjectURL(blob);
      outputEl.appendChild(img);
      return;
    }
    const blob = new Blob([bytes], mt ? { type: mt } : undefined);
    const link = document.createElement('a');
    link.href = URL.createObjectURL(blob);
    link.download = 'artifact';
    link.textContent = 'Download artifact' + (mt ? ' (' + mt + ')' : '');
    outputEl.appendChild(link);
  }

  // Read and validate a pipe-task duration from a number input. Pipe tasks
  // require an integer number of MINUTES in [1, 43200] (1 minute … 30 days).
  // The SDK also validates before the request leaves the browser; this surfaces
  // a friendly error first and keeps the bad value from being sent.
  function readPipeDuration(el) {
    const v = parseInt(el && el.value, 10);
    if (!Number.isInteger(v) || v < 1 || v > 43200) {
      throw new Error('Duration must be a whole number of minutes between 1 and 43200.');
    }
    return v;
  }

  // Maximum time to wait for the embed-auth widget script (injected in
  // index.html) to define window.BlocksAuth.
  const WIDGET_READY_TIMEOUT_MS = 10000;

  // Resolve once the widget has defined window.BlocksAuth, or to false after
  // WIDGET_READY_TIMEOUT_MS if it never loads. The widget is a large
  // cross-origin bundle injected via a dynamically-created <script>; a
  // dynamically-inserted async=false script is NOT ordered against this
  // deferred app.js, so app.js can run first. Reading window.BlocksAuth
  // synchronously would then see it undefined. Wait instead of assuming.
  function whenBlocksAuthReady(timeoutMs) {
    return new Promise(function (resolve) {
      if (typeof BlocksAuth !== 'undefined') { resolve(true); return; }
      let waited = 0;
      const step = 50;
      const timer = setInterval(function () {
        if (typeof BlocksAuth !== 'undefined') {
          clearInterval(timer);
          resolve(true);
        } else if ((waited += step) >= timeoutMs) {
          clearInterval(timer);
          resolve(false);
        }
      }, step);
    });
  }

  // Single-agent scaffold: signInAndGetClient returns one TaskClient.
  let clients = null;

  function embedBackendBaseUrl() {
    const dev = (typeof window !== 'undefined' && window.__BLOCKS_EMBED_DEV__) || null;
    return (dev && dev.backendBaseUrl) ? dev.backendBaseUrl : "https://app.blocks.ai";
  }

  async function attemptSignIn() {
    authError.textContent = '';
    if (!(await whenBlocksAuthReady(WIDGET_READY_TIMEOUT_MS))) {
      authError.textContent = 'The Blocks auth widget failed to load. Check your network connection and reload.';
      return false;
    }
    try {
      const client = await BlocksAuth.signInAndGetClient({ agent: "complex_multi_input", backendBaseUrl: embedBackendBaseUrl() });
      clients = { ["complex_multi_input"]: client };
      signInBtn.hidden = true;
      signOutBtn.hidden = false;
      if (clients["complex_multi_input"]) document.getElementById('section-complex_multi_input').hidden = false;
      return true;
    } catch (err) {
      authError.textContent = blocksErrorMessage(err);
      return false;
    }
  }

  signInBtn.addEventListener('click', attemptSignIn);

  // Auto-resume on page load: silent refresh ONLY when the stored partition exactly matches this page's (backend, origin, agents); otherwise wait for click.
  async function hasExactStoredEmbedSession() {
    try {
      if (typeof BlocksAuth === 'undefined' || typeof BlocksAuth.computePartitionKey !== 'function') return false;
      const raw = localStorage.getItem('blocks-auth-active-sessions-v1');
      if (!raw) return false;
      const arr = JSON.parse(raw);
      if (!Array.isArray(arr) || arr.length === 0) return false;
      const backendBaseUrl = embedBackendBaseUrl();
      const pageOrigin = window.location.origin;
      const agentNames = ["complex_multi_input"];
      const expected = await BlocksAuth.computePartitionKey({ backendBaseUrl, pageOrigin, agentNames });
      return arr.some(function (entry) { return entry && entry.partitionKey === expected; });
    } catch (_) {
      return false;
    }
  }
  whenBlocksAuthReady(WIDGET_READY_TIMEOUT_MS).then(function () {
    hasExactStoredEmbedSession().then(function (yes) {
      if (yes) attemptSignIn();
    });
  });

  signOutBtn.addEventListener('click', async () => {
    // signOut clears the partitioned localStorage entry for this origin;
    // reload to reset the in-page state.
    await BlocksAuth.signOut();
    window.location.reload();
  });

  // === Agent: complex_multi_input ===
  document.getElementById('send-complex_multi_input').addEventListener('click', async () => {
    const sendBtn = document.getElementById('send-complex_multi_input');
    const outputEl = document.getElementById('output-complex_multi_input');
    const streamEl = document.getElementById('stream-complex_multi_input');
    streamEl.textContent = '';
    outputEl.textContent = '';
    sendBtn.disabled = true;
    const renderedRefs = new Set();
    try {
      const client = clients["complex_multi_input"];
      const requestParts = [];
      // input "in1" is form-class (application/json) — wire shape is
      // { partId, text: <JSON-encoded value> } per SDK_CONTRACT §8.6.2g.
      const ta_0 = document.getElementById("input-complex_multi_input-in1");
      try { JSON.parse(ta_0.value); } catch (e) { throw new Error('input ' + "in1" + ': invalid JSON: ' + e.message); }
      requestParts.push({ partId: "in1", text: ta_0.value });
      // input "in2" is text-class (text/plain) — wire shape is
      // { partId, text: <raw string> } per SDK_CONTRACT §8.6.2g.
      const ta_1 = document.getElementById("input-complex_multi_input-in2");
      requestParts.push({ partId: "in2", text: ta_1.value });
      // TODO: agent did not declare a schema for input "in2". Replace the
      //       textarea default with whatever your handler accepts.
      // input "in3" is form-class (application/json) — wire shape is
      // { partId, text: <JSON-encoded value> } per SDK_CONTRACT §8.6.2g.
      const ta_2 = document.getElementById("input-complex_multi_input-in3");
      try { JSON.parse(ta_2.value); } catch (e) { throw new Error('input ' + "in3" + ': invalid JSON: ' + e.message); }
      requestParts.push({ partId: "in3", text: ta_2.value });
      // input "in4" is form-class (application/json) — wire shape is
      // { partId, text: <JSON-encoded value> } per SDK_CONTRACT §8.6.2g.
      const ta_3 = document.getElementById("input-complex_multi_input-in4");
      try { JSON.parse(ta_3.value); } catch (e) { throw new Error('input ' + "in4" + ': invalid JSON: ' + e.message); }
      requestParts.push({ partId: "in4", text: ta_3.value });
      // input "in5" is form-class (application/json) — wire shape is
      // { partId, text: <JSON-encoded value> } per SDK_CONTRACT §8.6.2g.
      const ta_4 = document.getElementById("input-complex_multi_input-in5");
      try { JSON.parse(ta_4.value); } catch (e) { throw new Error('input ' + "in5" + ': invalid JSON: ' + e.message); }
      requestParts.push({ partId: "in5", text: ta_4.value });
      // TODO: card declares additional inputs beyond the generator's
      //       complexity ceiling. Wire these manually:
      //   - in6 (application/json)
      const session = await client.sendMessage({
        agentName: "complex_multi_input",
        taskKind: "request",
        requestParts,
      });
      // Output rendering is dispatched via onArtifact, switching on
      // event.outputId. outputId is OPTIONAL per SDK_CONTRACT §9.1, so
      // untagged or unknown artifacts fall to a mimeType-based renderer.
      session.onArtifact(async (event) => {
        if (renderedRefs.has(event.artifactRef)) return;
        renderedRefs.add(event.artifactRef);
        let bytes;
        try {
          const downloaded = await session.downloadArtifact(event.artifactRef);
          bytes = downloaded.data;
        } catch (err) {
          outputEl.textContent += '\n[download failed: ' + err.message + ']';
          return;
        }
        switch (event.outputId) {
          // === Output: "out1" (text/plain, guaranteed=true) ===
          case "out1": {
            outputEl.textContent += new TextDecoder().decode(bytes);
            break;
          }
          // === Output: "out2" (application/json, guaranteed=false) ===
          case "out2": {
            const parsed = JSON.parse(new TextDecoder().decode(bytes));
            outputEl.textContent += JSON.stringify(parsed, null, 2);
            break;
          }
          // === Output: "out3" (application/pdf, guaranteed=false) ===
          case "out3": {
            // TODO: output "out3" is application/pdf. Rendered as a download link;
            //       replace with whatever your UI needs.
            const blob = new Blob([bytes], { type: "application/pdf" });
            const link = document.createElement('a');
            link.href = URL.createObjectURL(blob);
            link.download = "out3";
            link.textContent = 'Download ' + "out3";
            outputEl.appendChild(link);
            break;
          }
          default: {
            // Untagged or unknown outputId. Render based on the artifact's
            // own mimeType rather than guessing which declared output it
            // was meant for.
            renderArtifactByMime(bytes, event.artifactRef.mimeType, outputEl);
          }
        }
      });
      // TODO: card declares additional outputs beyond the generator's
      //       complexity ceiling. Add cases manually:
      //   - out4 (image/png)
      // === Stream: "events_a" (events, outbound) ===
      // Filter on declaredStream (the card key); streamId is a runtime-
      // generated instance id and won't match the card key.
      // If declaredStream is undefined the agent didn't tag this stream
      // with a card key — the filter falls through and we ignore the stream.
      session.onStream(async (streamRef) => {
        if (streamRef.descriptor.declaredStream !== "events_a") return;
        const stream = streamRef.open();
        try {
          for await (const ev of stream.events()) {
            streamEl.textContent += JSON.stringify(ev) + '\n';
          }
        } catch (err) {
          streamEl.textContent += '\n[stream error: ' + err.message + ']';
        }
      });
      // === Stream: "events_b" (bytes, outbound) ===
      // Filter on declaredStream (the card key); streamId is a runtime-
      // generated instance id and won't match the card key.
      // If declaredStream is undefined the agent didn't tag this stream
      // with a card key — the filter falls through and we ignore the stream.
      // Note: shared-affinity stream — see SDK_CONTRACT §8.4.1a; do not
      //       call stream.end() on the inbound side.
      session.onStream(async (streamRef) => {
        if (streamRef.descriptor.declaredStream !== "events_b") return;
        const stream = streamRef.open();
        try {
          for await (const chunk of stream.bytes()) {
            streamEl.textContent += new TextDecoder().decode(chunk);
          }
        } catch (err) {
          streamEl.textContent += '\n[stream error: ' + err.message + ']';
        }
      });
      // TODO: card declares additional outbound stream "events_c" (events); generator
      //       complexity ceiling reached. Wire it manually following the same
      //       descriptor.declaredStream pattern below.
      const terminal = await session.waitForTerminal();
      if (terminal.state !== 'completed') {
        outputEl.textContent += '\n[' + (terminal.error || terminal.reason || 'task ' + terminal.state) + ']';
      }
      for (const ref of session.listArtifacts()) {
        if (renderedRefs.has(ref)) continue;
        renderedRefs.add(ref);
        try {
          const downloaded = await session.downloadArtifact(ref);
          renderArtifactByMime(downloaded.data, ref.mimeType, outputEl);
        } catch (err) {
          outputEl.textContent += '\n[download failed: ' + err.message + ']';
        }
      }
    } catch (err) {
      outputEl.textContent += '\n[' + blocksErrorMessage(err) + ']';
    } finally {
      sendBtn.disabled = false;
    }
  });

})();
