"""
Agent Registry - REST-based agent registration and discovery.

All registry operations (register, fetch, get, remove) use the server-side
REST endpoints at /api/v1/registry/agents which handle registry metadata operations,
membership indexing, and audit events server-side.
"""

from __future__ import annotations

import json
import logging
import os
import platform
import random
import re
import time
from dataclasses import dataclass, field
from typing import Any, Callable, Dict, List, Literal, Optional, TypeVar, Union

from .channel_manager import (
    normalize_tag_slug,
    registry_all_channel,
    registry_tag_channel,
    registry_log_channel,
    registry_visibility_channel,
)
from .protocol_version import (
    CURRENT_PROTOCOL_VERSION,
    PROTOCOL_VERSION_HEADER,
    SDK_VERSION,
    SUPPORTED_PROTOCOL_VERSIONS,
)
from .write_affinity import capture_affinity, inject_affinity

logger = logging.getLogger(__name__)

# ============================================================================
# Types
# ============================================================================

T = TypeVar("T")


@dataclass
class AgentScaling:
    """Scaling configuration for multi-instance support."""

    expected_instances: int
    concurrency: int
    max_pending_backlog: Optional[int] = None    # Default: 10 (applied at read time by On Interval function)
    max_running_time_sec: Optional[int] = None   # No default (if unset, stuck-running detection is skipped)


@dataclass
class AgentCard:
    """Agent card payload (new 9-section structure) -- authored by developers in agent-card.json.

    Required sections: identity, capabilities, tags, runtime.
    Optional sections: io, streams, security, services, extensions.

    ``display_name`` and ``agent_name`` are convenience fields that map to
    ``identity.displayName`` and ``identity.agentName`` in the wire format.
    They are serialized into the identity dict by ``_card_to_dict``.
    """

    display_name: str = ""
    agent_name: str = ""
    identity: Dict[str, Any] = field(default_factory=dict)
    capabilities: Dict[str, Any] = field(default_factory=dict)
    tags: List[Dict[str, Any]] = field(default_factory=list)
    runtime: Dict[str, Any] = field(default_factory=dict)
    io: Optional[Dict[str, Any]] = None
    streams: Optional[Dict[str, Any]] = None
    security: Optional[Dict[str, Any]] = None
    services: Optional[Dict[str, Any]] = None
    extensions: Optional[Dict[str, Any]] = None


@dataclass
class OutputAgentCard:
    """Agent card payload (output/public schema) -- served by the API.

    Same as AgentCard minus the runtime section.
    """

    identity: Dict[str, Any] = field(default_factory=dict)
    capabilities: Optional[Dict[str, Any]] = None
    tags: Optional[List[Dict[str, Any]]] = None
    io: Optional[Dict[str, Any]] = None
    streams: Optional[Dict[str, Any]] = None
    security: Optional[Dict[str, Any]] = None
    services: Optional[Dict[str, Any]] = None
    extensions: Optional[Dict[str, Any]] = None


@dataclass
class AgentEntry:
    """Agent entry returned from registry queries.

    ``listing`` carries the server-side visibility tier; valid values are
    ``'private' | 'public'`` (typed as ``Optional[str]`` for dataclass
    defensiveness against unknown server values).

    ``billing_mode`` is the server-derived billing tier used by the SDK
    to select the PubNub keyset: ``'paid'`` routes to the network keyset,
    ``'free'`` (or missing) routes to the playground keyset.
    """

    agent_name: str
    name: str
    description: Optional[str] = None
    tags: Optional[List[Any]] = None
    scaling: Optional[Any] = None
    card: Optional[Any] = None
    card_ref: Optional[str] = None
    card_summary: Optional[str] = None
    listing: Optional[str] = None
    billing_mode: Optional[Literal["free", "paid"]] = None
    created_at: Optional[str] = None
    updated_at: Optional[str] = None


@dataclass
class ConnectAgentOptions:
    """Options for registering an agent.

    instance_id is auto-generated by start_agent_instance, not caller-supplied.

    ``listing`` valid values are ``'private' | 'public'`` (typed as
    ``Optional[str]`` for dataclass defensiveness). When omitted, the
    server applies its default (``'public'``).

    ``billing_mode`` is REQUIRED on the wire — the backend connect Zod
    schema requires it (Billing Mode Contract Phase 2). It is populated
    by ``start_agent_instance`` from the registry GET at boot; there is
    no provider-supplied override path. Typed as
    ``Optional[Literal['free', 'paid']]`` for dataclass defaulting only;
    in practice every real call sets it.
    """

    instance_id: Optional[str] = None
    description: Optional[str] = None
    # AgentTag objects ({id, name, description?, examples?}), matching Node
    # ConnectAgentOptions.tags: AgentTag[]. (The pre-rename `skills` field was
    # List[str] here, which diverged from Node; the rename aligns the shape.)
    tags: Optional[List[Dict[str, Any]]] = None
    scaling: Optional[AgentScaling] = None
    card: Optional[Union[AgentCard, Dict[str, Any]]] = None
    card_ref: Optional[str] = None
    card_summary: Optional[str] = None
    listing: Optional[str] = None
    billing_mode: Optional[Literal["free", "paid"]] = None
    supported_task_kinds: Optional[List[str]] = None
    actor: Optional[str] = None
    request_id: Optional[str] = None
    base_url: Optional[str] = None
    agent_auth: Optional[Any] = None  # AgentAuth instance for API key-based auth


@dataclass
class AgentRegistryResult:
    """Result of fetching the agent registry."""

    agents: List[AgentEntry]
    next: Optional[str] = None
    total_count: Optional[int] = None


@dataclass
class RegistryAuditEvent:
    """Audit log event for registry changes."""

    event: Literal[
        "registry.agent.upsert",
        "registry.agent.delete",
        "registry.membership.add",
        "registry.membership.remove",
        "registry.bootstrap",
        "registry.clear",
    ]
    ts: int
    source: str
    agent_name: Optional[str] = None
    visibility: Optional[Literal["public", "private"]] = None
    tags: Optional[List[str]] = None
    card_hash: Optional[str] = None
    card_ref: Optional[str] = None
    summary_hash: Optional[str] = None
    channel: Optional[str] = None
    action: Optional[str] = None
    request_id: Optional[str] = None
    actor: Optional[str] = None
    etags: Optional[Dict[str, Optional[str]]] = None
    note: Optional[str] = None


# ============================================================================
# Helpers
# ============================================================================

# Transient error indicators for Python network exceptions
_TRANSIENT_ERROR_INDICATORS = (
    "Name or service not known",
    "getaddrinfo failed",
    "Connection refused",
    "Connection reset",
    "timed out",
    "NetworkIssues",
)


def _detect_device_os() -> str:
    try:
        return platform.system().lower()
    except Exception:
        return "unknown"


_SDK_LANGUAGE = "Python"


def with_retry(
    fn: Callable[[], T],
    max_retries: int = 3,
    base_delay_ms: int = 500,
) -> T:
    """
    Retry helper for transient network errors (DNS failures, timeouts, etc.).

    Implements exponential backoff with jitter, matching the Node implementation.
    """
    last_error: Optional[Exception] = None

    for attempt in range(max_retries):
        try:
            return fn()
        except Exception as err:
            last_error = err
            error_str = str(err)
            is_transient = any(
                indicator in error_str for indicator in _TRANSIENT_ERROR_INDICATORS
            )

            if not is_transient or attempt == max_retries - 1:
                raise

            delay_s = (base_delay_ms * (2 ** attempt) + random.random() * 100) / 1000.0
            time.sleep(delay_s)

    # Should not reach here, but satisfy type checker
    raise last_error  # type: ignore[misc]


def _card_to_dict(card: Union[AgentCard, Dict[str, Any], None]) -> Optional[Dict[str, Any]]:
    """Convert an AgentCard dataclass or dict to a plain dict for JSON serialization."""
    if card is None:
        return None
    if isinstance(card, dict):
        return card
    # Build identity dict with displayName and agentName
    identity = dict(card.identity)
    if card.display_name:
        identity["displayName"] = card.display_name
    if card.agent_name:
        identity["agentName"] = card.agent_name
    # Convert dataclass to dict (new 9-section structure)
    result: Dict[str, Any] = {
        "identity": identity,
        "capabilities": card.capabilities,
        "tags": card.tags,
        "runtime": card.runtime,
    }
    if card.io is not None:
        result["io"] = card.io
    if card.streams is not None:
        result["streams"] = card.streams
    if card.security is not None:
        result["security"] = card.security
    if card.services is not None:
        result["services"] = card.services
    if card.extensions is not None:
        result["extensions"] = card.extensions
    return result


# ============================================================================
# REST Helpers
# ============================================================================


def _get_base_url(override_url: Optional[str] = None) -> str:
    """Resolve the backend base URL from an explicit override."""
    if override_url:
        return override_url.rstrip("/")
    raise ValueError("[AgentRegistry] baseUrl is required: provide it via options or CDM config")


def _registry_url(
    query: Optional[Dict[str, str]] = None,
    base_url: Optional[str] = None,
) -> str:
    """Build a registry REST endpoint URL."""
    from urllib.parse import urlencode

    url = f"{_get_base_url(base_url)}/api/v1/registry/agents"
    if query:
        filtered = {k: v for k, v in query.items() if v}
        if filtered:
            url += "?" + urlencode(filtered)
    return url


def _registry_fetch(
    url: str,
    method: str = "GET",
    body: Optional[bytes] = None,
    headers: Optional[Dict[str, str]] = None,
) -> Optional[Any]:
    """
    Perform an HTTP request to the registry endpoint.

    Returns parsed JSON on success, None on 404, raises on other errors.
    """
    import ssl
    import urllib.request
    import urllib.error

    import certifi

    ssl_ctx = ssl.create_default_context(cafile=certifi.where())
    default_headers = {PROTOCOL_VERSION_HEADER: CURRENT_PROTOCOL_VERSION}
    if headers:
        default_headers.update(headers)
    inject_affinity(default_headers)
    req = urllib.request.Request(
        url,
        data=body,
        headers=default_headers,
        method=method,
    )

    try:
        with urllib.request.urlopen(req, context=ssl_ctx, timeout=30) as resp:
            capture_affinity(resp)
            resp_body = resp.read().decode("utf-8")
            if not resp_body:
                return {}
            return json.loads(resp_body)
    except urllib.error.HTTPError as exc:
        if exc.code == 404:
            return None
        resp_body = exc.read().decode("utf-8") if exc.fp else ""
        message = f"HTTP {exc.code}"
        try:
            err_json = json.loads(resp_body)
            if isinstance(err_json, dict) and err_json.get("message"):
                message = err_json["message"]
        except (json.JSONDecodeError, ValueError):
            pass
        raise RuntimeError(f"[AgentRegistry] Request failed: {message}") from exc
    except urllib.error.URLError as exc:
        raise RuntimeError(f"[AgentRegistry] Request failed: {exc.reason}") from exc
    except OSError as exc:
        raise RuntimeError(f"[AgentRegistry] Request failed: {exc}") from exc


# ============================================================================
# Response Mapping
# ============================================================================


def _map_server_agent_to_entry(agent: Dict[str, Any]) -> AgentEntry:
    """Map server JSON response to an AgentEntry."""
    return AgentEntry(
        agent_name=agent.get("agentName", ""),
        name=agent.get("name") or agent.get("agentName", ""),
        description=agent.get("description"),
        tags=agent.get("tags"),
        scaling=agent.get("scaling"),
        card=agent.get("card"),
        card_ref=agent.get("cardRef"),
        card_summary=agent.get("cardSummary"),
        listing=agent.get("listing"),
        billing_mode=agent.get("billingMode"),
        created_at=agent.get("registeredAt"),
    )


# ============================================================================
# Registry Operations
# ============================================================================


@dataclass
class ConnectAgentResult:
    """Result of registering an agent."""

    pam_token: Optional[str] = None
    agent_id: Optional[str] = None
    control_channel: Optional[str] = None


def _assert_no_legacy_skills_field(card: Optional[Union[AgentCard, Dict[str, Any]]]) -> None:
    """Reject the legacy ``skills`` field on an agent-card dict.

    ``skills`` was renamed to ``tags``; there is no wire/SDK alias. Without
    this guard, Python callers who still pass ``{"skills": [...]}`` would
    silently send the field over the wire and only see the backend's
    generic rejection. This fails fast on the client side with an
    actionable error.
    """
    if card is None:
        return
    if isinstance(card, dict) and "skills" in card:
        raise ValueError(
            "[blocks-network] agent-card field `skills` was renamed to `tags`. "
            "Action: rename the field in your code (or in any agent-card.json you load) — "
            "same shape, only the key name changes. This SDK ships no compatibility alias. "
            "If you publish via `blocks-cli`, upgrading the CLI rewrites the field for you, "
            "but programmatic callers (this SDK) must rename."
        )


def connect_agent(
    agent_name: str,
    options: Optional[ConnectAgentOptions] = None,
) -> ConnectAgentResult:
    """
    Register or update an agent in the registry.

    Sends a POST request to the dedicated registry endpoint which handles
    all registry metadata operations (UUID metadata, memberships, audit events)
    server-side.

    Args:
        agent_name: The agent name identifier.
        options: Registration options including instance_id, card, etc.

    Returns:
        ConnectAgentResult with optional pamToken from the server.
    """
    if not re.fullmatch(r'[a-zA-Z0-9_]+', agent_name):
        raise ValueError(
            "agent_name must contain only alphanumeric characters "
            "and underscores (no hyphens)"
        )

    if options is None:
        options = ConnectAgentOptions()

    _assert_no_legacy_skills_field(options.card)

    cli_version = os.environ.get("BLOCKS_CLI_VERSION") or None

    result_holder: Dict[str, Any] = {}
    agent_auth = options.agent_auth

    if agent_auth is None:
        raise RuntimeError(
            "[AgentRegistry] agent_auth is required. "
            "Set BLOCKS_API_KEY and pass agent_auth to connect_agent."
        )

    # Connect payload: runtime-only fields for /auth/agent/connect.
    # Card, description, cardRef, cardSummary, and tags are sent
    # by `blocks publish`, not by the SDK at connect time.
    #
    # ``billingMode`` is the registry-resolved value forwarded by
    # ``start_agent_instance``. Backend connect Zod schema (Billing Mode
    # Contract Phase 2) requires it; the SDK does not derive or override
    # the value from anywhere except the registry GET.
    payload = {
        "agentName": agent_name,
        "instanceId": options.instance_id,
        "billingMode": options.billing_mode,
        "listing": options.listing,
        "expectedInstances": options.scaling.expected_instances if options.scaling else None,
        "concurrency": options.scaling.concurrency if options.scaling else None,
        "maxPendingBacklog": options.scaling.max_pending_backlog if options.scaling else None,
        "maxRunningTimeSec": options.scaling.max_running_time_sec if options.scaling else None,
        "deviceOs": _detect_device_os(),
        "sdkLanguage": _SDK_LANGUAGE,
        "sdkVersion": SDK_VERSION,
        "protocolVersions": list(SUPPORTED_PROTOCOL_VERSIONS),
        "preferredProtocolVersion": CURRENT_PROTOCOL_VERSION,
        "cliVersion": cli_version,
    }
    # Strip None values -- backend Zod schema treats null as invalid for optional fields
    payload = {k: v for k, v in payload.items() if v is not None}

    def _do_auth_register() -> None:
        from .agent_auth import AgentAuthFatalError

        try:
            resp_data = agent_auth.init(registration_payload=payload)
            if isinstance(resp_data, dict):
                result_holder.update(resp_data)
        except AgentAuthFatalError:
            raise
        except Exception as exc:
            raise RuntimeError(f"[AgentRegistry] Registration failed: {exc}") from exc

    with_retry(_do_auth_register)

    pam_token = result_holder.get("pamToken")
    agent_id = result_holder.get("agentId")
    control_channel = result_holder.get("controlChannel")
    return ConnectAgentResult(
        pam_token=pam_token if isinstance(pam_token, str) else None,
        agent_id=agent_id if isinstance(agent_id, str) else None,
        control_channel=control_channel if isinstance(control_channel, str) else None,
    )


def get_agent(
    agent_name: str,
    base_url: Optional[str] = None,
    api_key: Optional[str] = None,
) -> Optional[AgentEntry]:
    """
    Get a single agent by name.

    Pass ``api_key`` to authenticate the lookup. Without it, the registry
    endpoint returns 404 for private agents (existence-privacy) and the SDK
    cannot resolve its own published record — leaving keyset routing stranded
    on the playground default while connect mints a PAM token for the network
    keyset.

    Args:
        agent_name: The agent name identifier to look up.
        base_url: Optional base URL override.
        api_key: Optional Blocks API key for authenticated lookup of private agents.

    Returns:
        AgentEntry if found, None otherwise.
    """
    url = _registry_url(query={"agentName": agent_name}, base_url=base_url)
    headers = {"Authorization": f"Bearer {api_key}"} if api_key else None

    result = with_retry(lambda: _registry_fetch(url, headers=headers))

    if result is None:
        return None

    agent = result.get("agent")
    if not agent:
        return None

    return _map_server_agent_to_entry(agent)


def fetch_agent_registry(
    limit: int = 100,
    cursor: Optional[str] = None,
    base_url: Optional[str] = None,
) -> AgentRegistryResult:
    """
    Fetch the agent registry (all agents).

    Args:
        limit: Maximum number of agents to return (default 100).
        cursor: Pagination cursor for fetching next page.
        base_url: Optional base URL override.

    Returns:
        AgentRegistryResult with the list of agents.
    """
    query: Dict[str, str] = {"include": "full"}
    if limit:
        query["limit"] = str(limit)
    if cursor:
        query["cursor"] = cursor

    url = _registry_url(query, base_url=base_url)

    result = with_retry(lambda: _registry_fetch(url))

    if result is None:
        return AgentRegistryResult(agents=[], total_count=0)

    agents = [_map_server_agent_to_entry(a) for a in result.get("agents", [])]
    return AgentRegistryResult(
        agents=agents,
        next=result.get("next"),
        total_count=result.get("totalCount"),
    )


def fetch_agents_by_tag(
    tag: str,
    limit: int = 100,
    cursor: Optional[str] = None,
    base_url: Optional[str] = None,
) -> AgentRegistryResult:
    """
    Fetch agents filtered by tag.

    Args:
        tag: Tag string to filter by.
        limit: Maximum number of agents to return (default 100).
        cursor: Pagination cursor for fetching next page.
        base_url: Optional base URL override.

    Returns:
        AgentRegistryResult with matching agents.
    """
    query: Dict[str, str] = {"include": "full", "tag": tag}
    if limit:
        query["limit"] = str(limit)
    if cursor:
        query["cursor"] = cursor

    url = _registry_url(query, base_url=base_url)

    result = with_retry(lambda: _registry_fetch(url))

    if result is None:
        return AgentRegistryResult(agents=[], total_count=0)

    agents = [_map_server_agent_to_entry(a) for a in result.get("agents", [])]
    return AgentRegistryResult(
        agents=agents,
        next=result.get("next"),
        total_count=result.get("totalCount"),
    )


def fetch_agents_by_listing(
    listing: Literal["private", "public"],
    limit: int = 100,
    cursor: Optional[str] = None,
    base_url: Optional[str] = None,
) -> AgentRegistryResult:
    """
    Fetch agents filtered by listing type.

    Args:
        listing: Listing type to filter by ('private' or 'public').
        limit: Maximum number of agents to return (default 100).
        cursor: Pagination cursor for fetching next page.
        base_url: Optional base URL override.

    Returns:
        AgentRegistryResult with matching agents.
    """
    query: Dict[str, str] = {"include": "full", "listing": listing}
    if limit:
        query["limit"] = str(limit)
    if cursor:
        query["cursor"] = cursor

    url = _registry_url(query, base_url=base_url)

    result = with_retry(lambda: _registry_fetch(url))

    if result is None:
        return AgentRegistryResult(agents=[], total_count=0)

    agents = [_map_server_agent_to_entry(a) for a in result.get("agents", [])]
    return AgentRegistryResult(
        agents=agents,
        next=result.get("next"),
        total_count=result.get("totalCount"),
    )


def remove_agent(
    agent_name: str,
    base_url: Optional[str] = None,
    agent_auth: Optional[Any] = None,
) -> bool:
    """
    Remove an agent from the registry.

    Args:
        agent_name: The agent name identifier to remove.
        base_url: Optional base URL override.
        agent_auth: Optional AgentAuth instance for API key-based auth.

    Returns:
        True if the agent was removed, False if it didn't exist.
    """
    url = _registry_url(query={"agentName": agent_name}, base_url=base_url)

    if agent_auth is not None:
        def _do_auth_delete() -> bool:
            resp_data, status = agent_auth.authenticated_request(url, method="DELETE")
            return status != 404

        return with_retry(_do_auth_delete)

    result = with_retry(lambda: _registry_fetch(url, method="DELETE"))

    return result is not None


# ============================================================================
# Re-exports for convenience
# ============================================================================

__all__ = [
    # Types
    "AgentScaling",
    "AgentCard",
    "OutputAgentCard",
    "AgentEntry",
    "ConnectAgentOptions",
    "ConnectAgentResult",
    "AgentRegistryResult",
    "RegistryAuditEvent",
    # Helpers
    "with_retry",
    # Registry Operations
    "connect_agent",
    "fetch_agent_registry",
    "fetch_agents_by_tag",
    "fetch_agents_by_listing",
    "get_agent",
    "remove_agent",
    # Re-exports from channel_manager
    "registry_all_channel",
    "registry_tag_channel",
    "registry_visibility_channel",
    "registry_log_channel",
    "normalize_tag_slug",
]
